apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaiburr-deployment
  labels:
    app: kaiburr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kaiburr
  template:
    metadata:
      labels:
        app: kaiburr
    spec:
      containers:
        - name: kaiburr
          image: kaiburr:v1
          env:
            - name: MONGO_URI
              value: "mongodb://mongo-service:27017/rest-api-db"
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: rest-api-service
  labels:
    app: rest-api
spec:
  selector:
    app: rest-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer
